apiVersion : apps/v1
kind: Deployment
metadata:
  name: test-sqlconnection-deployment
  labels:
    app : test-sqlconnection-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      project: test-sqlconnection
  template:
    metadata:
      labels:
        project: test-sqlconnection   # Service will look for those PODS Labels!!!
    spec:
      containers:
        - name : test-sqlconnection
          image: nairobipoccontainerreg.azurecr.io/test/sqltest:latest
          ports:
            - containerPort: 80
          env:
            - name: SERVER
              value: "nairobi-production-sql-cet.azure.cet.ac.il"
            - name: USER
              value: "nairobi"
            - name: PASS
              value: "StarTr3ck!"
            - name: DB
              value: "test-sql"

---
apiVersion: v1
kind: Service
metadata:
  name: test-sqlconnection-service
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
  labels:
    env  : prod
    owner: Alexk
spec:
  selector:
    project: test-sqlconnection    # Selecting PODS with those Labels
  ports:
    - name      : app-list
      protocol  : TCP
      port      : 80  # Port on Load Balancer
      targetPort: 80  # Port on POD
  type: LoadBalancer